### ISSUE TITLE
Double Object Files

### ISSUE THREAD

**Issue by Nopey** [SLikeSoft/SLikeNet#13]
I noticed that LibStatic and DLL compile their own object file for each and every `.cpp` file.
Here is a section of the `find` results
```
build/raknet-build/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/src/StringTable.cpp.o
build/raknet-build/Lib/LibStatic/CMakeFiles/RakNetLibStatic.dir/__/__/Source/src/DS_HuffmanEncodingTree.cpp.o
build/raknet-build/Lib/DLL/CMakeFiles/RakNetDLL.dir/__/__/Source/src/CloudClient.cpp.o
build/raknet-build/Lib/DLL/CMakeFiles/RakNetDLL.dir/__/__/Source/src/FileOperations.cpp.o
...
build/raknet-build/Lib/DLL/CMakeFiles/RakNetDLL.dir/__/__/Source/src/StringTable.cpp.o
build/raknet-build/Lib/DLL/CMakeFiles/RakNetDLL.dir/__/__/Source/src/DS_HuffmanEncodingTree.cpp.o

```
It seems they are trying to build those files in the parent directory, but the periods got escaped into underscores.

**Comment by Nopey** [comment]
Perhaps making `RakNetLibStatic` and `RakNetDLL` into one project would fix this?

**Comment by Luke1410** [comment]
To my knowledge (correct me if I'm wrong), sharing the same intermediate directory for building static and shared projects is not portable. F.e. on Windows __declspec(dllexport) would be used to add export directives to the object files when building shared libraries (i.e. DLLs) [1]. This would render the object files incompatible when building a static library.
Hence, using two different projects for static and shared libraries appears to be correct. I'm certainly open for a different opinion here.

[1] https://msdn.microsoft.com/en-us/library/a90k134d.aspx

On the point of escaping the periods: As far as I can see it, this is normal behavior. Note that the projects are located under src/Lib/DLL (or src/Lib/LibStatic respectively) while the source code the projects reference is located in src/Source/ . Hence, the relative path from the project directory is correctly set to ../../Source/src. From the cmake output I conclude that cmake translates this to an intermediate directory for the generated object files as shown in the output above. So, I'm failing to see what should go wrong here. Please reopen if you think that something was overlooked from our side.
