### ISSUE TITLE
German Symbol E4 in Copyright Notice's Limited Liability

### ISSUE THREAD

**Issue by Nopey** [SLikeSoft/SLikeNet#14]
haftungsbeschr�nkt displays with a rotated error square instead of an "ä" symbol.
Perhaps replace it with ä, or ae? ä in hexadecimal is `C3 A4`.

**Comment by Luke1410** [comment]
Good catch. The file encoding seems to be wrong. Should be UTF8 but is actually Windows 1252 (Western European). I'll see to correct this (internal case number: SLNET-116).

**Comment by Luke1410** [comment]
File encoding should be correct on master already and is expected to be included in SLikeNet 0.1.1.

**Comment by Luke1410** [comment]
SLikeNet 0.1.1 which contains the fix has just been released.
