### ISSUE TITLE
Whether SLikeNet can be integrated into the Java environment?

### ISSUE THREAD

**Issue by shuizhihun** [SLikeSoft/SLikeNet#17]
We're working on a game,The client of the game is developed in c++ and the server is developed in Java. We're going to use SLikeNet ,The problem we have is how to use SLikeNet on the server side, Whether SLikeNet has a Java version? What is the efficiency of using Java native to invoke SLikeNet ? other Suggestions? Thanks!

**Comment by OvermindDL1** [comment]
There is no Java version, you can use it from java by making java bindings for it (same as using any other native library in java) though.  :-)

For note, native marshalling in Java incurs an overhead because Java does not have an efficient FFI setup, but it's no worse than any other native binding in java either, but you'll probably want to optimize your binding for doing as much 'work' per call as possible.

**Comment by Luke1410** [comment]
@shuizhihun This is an interesting approach. Client written in C++ with the server backend running in Java. Can you describe the scope of your game a bit and the reasoning behind the decision of having the server side written in Java?

As @OvermindDL1 already stated, there is no native Java support in SLikeNet and to my knowledge there's also no port of RakNet to Java.

SLikeNet (and RakNet) is a cross-platform network engine, so it will work on Linux backends as well. Hence, from that technical side nothing should really prevent you from writing the backend in C++ as well, or not?

Usually one wants exactly the server-backend to be really performant, hence Java would not be my first choice here.

If you really want the server side to use SLikeNet/RakNet with the client using C++, an alternative to the approach @OvermindDL1 stated might be to process the SLikeNet/RakNet protocol directly in your Java server app. Also certain other features (f.e. the auto patcher) could be integrated on the server side on Java (i.e. an administration panel or whatever you have in mind). But all of this basically depends on your precise needs for your project/product.

**Comment by Kiddinglife** [comment]
@shuizhihun  rewrite Raknet with Java is easier than bindings.

**Comment by Luke1410** [comment]
Due to lack of any response within 2 months from the OP, I consider this issue answered. Feel free to reopen, if there was still any question left.
