### ISSUE TITLE
Improvement: Is it possible to improve raknet's network protocol based on rfc-4960-sctp?

### ISSUE THREAD

**Issue by Kiddinglife** [SLikeSoft/SLikeNet#24]
Hi there,
I am now implementing sctp in c language https://github.com/Kiddinglife/geconet
Anyone can tell me is it possible to improve raknet's protocol impl based on sctp rfc-4960?

**Comment by Luke1410** [comment]
It certainly is, but is quite an effort. I'll keep this open for as a feature request for the time being.

**Comment by Kiddinglife** [comment]
When raknet was originally appeared, rfc4960 had not been written. sctp is actually exactly same to raknet's reliable layer except that it does not have unreliable-unordering and unreliable-sequced trasmission. However, rfc4960 is very good documentation that we can follow to improve raknet's relaible layer. I will be working on this on my forked-repository.
