### ISSUE TITLE
improvement::need a directory where to put unit test codes

### ISSUE THREAD

**Issue by Kiddinglife** [SLikeSoft/SLikeNet#27]
Raknet 's existing test are all integrity and system tests but it really needs to be carefully unit-tested especially for the base modules like data structure, bitstream, reliable_layer, sick connection cases and much much more ....

**Comment by Luke1410** [comment]
We have set up such tests already in house and are improving the test coverage continuously. Before a release all the tests are being run to confirm nothing got broken. We are also working on a continuous test environment to run tests automatically prior to merging any pull request into the repository (atm this is still a manual process and hence not done for all pull requests/commits).

I'll put down a feature request regarding your point here to at least make a subset of the tests somehow available under the MIT license and get it integrated into the publicly available source code, so contributors have a way to verify no breakage of at least the basic functionality themselves.
(internal case number: SLNET-133).

For the time being however, don't hesitate to sent in any pull requests. If we find anything wrong while passing them through through our tests, that the issues will be dealt with.

**Comment by Kiddinglife** [comment]
this works on me. cheers!
