### ISSUE TITLE
Timeouts cannot be detected inside the client

### ISSUE THREAD

**Issue by 0x416c69** [SLikeSoft/SLikeNet#31]
Hi again.

I'm encountering a problem while detecting a timed out connection, I mean I want to be noticed when the server is timed out, I already tried packet ID_CONNECTION_LOST but it's not working, it just never calls.

**Comment by 0x416c69** [comment]
The problem was my code, sorry. I'm closing.

**Comment by Luke1410** [comment]
Good to hear you solved the issue. Don't hesitate to report any issue you might run into in the future.
