### ISSUE TITLE
SystemAddress FromString for localhost:port

### ISSUE THREAD

**Issue by Tomash667** [SLikeSoft/SLikeNet#46]
When using SystemAddress FromString like that:
```
SystemAddress adr;
adr.FromString("localhost:123", ':');
```
it will ignore port unless it's written like that "localhost123". There is no delimiter checking.

Possible fix: https://github.com/Tomash667/SLikeNet/commit/2701b19857f1d43550ae35f93b9d5acbdf1cd0ad

**Comment by Luke1410** [comment]
Thanks for the report Tomash667 and sorry for the delay in getting back to that. There are quite a few mishaps on that part of the code. We are currently revising that entire part and will have it resolved in a few hours.

Note that the patch you are suggesting only handles the case when using IPv4-only mode. The same issue however also exists in IPv6 mode in which case your fix won't suffice.

Internal case number: SLNET-263

**Comment by Luke1410** [comment]
The issue and multiple related ones have been resolved now. The fixes will be shipped with the upcoming version of SLikeNet.

**Comment by Luke1410** [comment]
SLikeNet 0.1.3 was released now (on 2019-08-23) which contains the fixes for this issue.
