### ISSUE TITLE
Mobile support.

### ISSUE THREAD

**Issue by juliolitwin** [SLikeSoft/SLikeNet#49]
Yo,

I know RakNet has support for mobile but in ReadMe from SLikeNet there is nothing saying in about mobile (android/ios). Mobile is not more longer supported?

Cheers.

**Comment by Luke1410** [comment]
Please refer to chapter 1.3 in the readme:
1.3 Changes between RakNet (4.081/4.082) and SLikeNet
[...]

There are also a couple of restrictions SLikeNet has when comparing its feature
set with RakNet. [...]
c) especially for the first versions we had to prioritize the work and had to
postpone work on certain parts but are planning to do so in later versions
(marked with "later in the following list)
[...]
The following list presents the known restrictions:
[...]
- limited support for iOS, Android, Windows Phone 8, Windows Store 8 (later)

That said, we are planning to add mobile support at a later point (case: SLNET-187) and have it on the radar.

**Comment by ArnisLielturks** [comment]
@jclitwin  We succesfully implemented it in Urho3D game engine and the samples works as excpected on  android and iOS devices if we're talking about client to sever and p2p modes + few plugins. See PR https://github.com/urho3d/Urho3D/pull/2302
